# Generated by Django 5.0.2 on 2024-05-24 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=250, verbose_name="Пароль")),
                ("name", models.CharField(max_length=3500, verbose_name="ФИО")),
                ("email", models.CharField(max_length=3500, verbose_name="E-mail")),
                ("phone", models.CharField(max_length=3500, verbose_name="Телефон")),
                (
                    "company",
                    models.CharField(max_length=3500, verbose_name="Название компании"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Закреплено за пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
