# Generated by Django 5.0.2 on 2024-05-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_jury_jurygroups"),
    ]

    operations = [
        migrations.AddField(
            model_name="jurygroups",
            name="name",
            field=models.CharField(
                default="new", max_length=250, verbose_name="Название группы"
            ),
            preserve_default=False,
        ),
    ]
